export {LoginPage} from "./logInPage"
export {ShoppingPage} from "./shoppingPage"
export {ContacPage} from "./contacPage"
export {BasePage} from "./basePage"
export {FormPage} from "./formpage"
export {UploadDownload} from "./upload-downloadPage"